server:
  port: 8080
spring:
  application:
    name: demo-sb-temporal-workflow-starter
  temporal:
    namespace: ${namespace:default}
    connection:
      target: ${temporal-frontend:127.0.0.1:7233}